/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * Bootcamp Treinos API
 * API para o bootcamp de treinos do FSC
 * OpenAPI spec version: 1.0.0
 */
import { customFetch } from '../../fetch';
export type GetHomeData200TodayWorkoutDay = {
  /** @pattern ^[cC][^\s-]{8,}$ */
  workoutPlanId: string;
  /** @pattern ^[cC][^\s-]{8,}$ */
  id: string;
  name: string;
  isRest: boolean;
  weekDay: 'MONDAY' | 'TUESDAY' | 'WEDNESDAY' | 'THURSDAY' | 'FRIDAY' | 'SATURDAY' | 'SUNDAY';
  /** @maximum 9007199254740991 */
  estimatedDurationInSeconds: number;
  coverImageUrl?: string;
  /**
   * @minimum 0
   * @maximum 9007199254740991
   */
  exercisesCount: number;
} |  | null;

export type GetHomeData200ConsistencyByDay = {[key: string]: {
  workoutDayCompleted: boolean;
  workoutDayStarted: boolean;
}};

export type GetHomeData200 = {
  activeWorkoutPlanId: string |  | null;
  todayWorkoutDay: GetHomeData200TodayWorkoutDay;
  /**
   * @minimum 0
   * @maximum 9007199254740991
   */
  workoutStreak: number;
  consistencyByDay: GetHomeData200ConsistencyByDay;
};

export type GetHomeData400 = {
  message: string;
  code: string;
};

export type GetHomeData401 = {
  message: string;
  code: string;
};

export type GetHomeData500 = {
  message: string;
  code: string;
};

export type ListWorkoutPlansParams = {
active?: string;
};

export type ListWorkoutPlans200WorkoutPlansItemWorkoutDaysItemWeekDay = typeof ListWorkoutPlans200WorkoutPlansItemWorkoutDaysItemWeekDay[keyof typeof ListWorkoutPlans200WorkoutPlansItemWorkoutDaysItemWeekDay];


export const ListWorkoutPlans200WorkoutPlansItemWorkoutDaysItemWeekDay = {
  MONDAY: 'MONDAY',
  TUESDAY: 'TUESDAY',
  WEDNESDAY: 'WEDNESDAY',
  THURSDAY: 'THURSDAY',
  FRIDAY: 'FRIDAY',
  SATURDAY: 'SATURDAY',
  SUNDAY: 'SUNDAY',
} as const;

export type ListWorkoutPlans200WorkoutPlansItemWorkoutDaysItemExercisesItem = {
  /** @pattern ^[cC][^\s-]{8,}$ */
  id: string;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  order: number;
  name: string;
  /** @maximum 9007199254740991 */
  sets: number;
  /** @maximum 9007199254740991 */
  reps: number;
  /** @maximum 9007199254740991 */
  restTimeInSeconds: number;
  /** @pattern ^[cC][^\s-]{8,}$ */
  workoutDayId: string;
};

export type ListWorkoutPlans200WorkoutPlansItemWorkoutDaysItem = {
  /** @pattern ^[cC][^\s-]{8,}$ */
  id: string;
  name: string;
  isRest: boolean;
  weekDay: ListWorkoutPlans200WorkoutPlansItemWorkoutDaysItemWeekDay;
  coverImageUrl?: string;
  /** @maximum 9007199254740991 */
  estimatedDurationInSeconds: number;
  exercises: ListWorkoutPlans200WorkoutPlansItemWorkoutDaysItemExercisesItem[];
};

export type ListWorkoutPlans200WorkoutPlansItem = {
  /** @pattern ^[cC][^\s-]{8,}$ */
  id: string;
  name: string;
  isActive: boolean;
  workoutDays: ListWorkoutPlans200WorkoutPlansItemWorkoutDaysItem[];
};

export type ListWorkoutPlans200 = {
  workoutPlans: ListWorkoutPlans200WorkoutPlansItem[];
};

export type ListWorkoutPlans401 = {
  message: string;
  code: string;
};

export type ListWorkoutPlans500 = {
  message: string;
  code: string;
};

export type CreateWorkoutPlanBodyWorkoutDaysItemWeekDay = typeof CreateWorkoutPlanBodyWorkoutDaysItemWeekDay[keyof typeof CreateWorkoutPlanBodyWorkoutDaysItemWeekDay];


export const CreateWorkoutPlanBodyWorkoutDaysItemWeekDay = {
  MONDAY: 'MONDAY',
  TUESDAY: 'TUESDAY',
  WEDNESDAY: 'WEDNESDAY',
  THURSDAY: 'THURSDAY',
  FRIDAY: 'FRIDAY',
  SATURDAY: 'SATURDAY',
  SUNDAY: 'SUNDAY',
} as const;

export type CreateWorkoutPlanBodyWorkoutDaysItemExercisesItem = {
  /**
   * @minimum 0
   * @maximum 9007199254740991
   */
  order: number;
  /** @minLength 1 */
  name: string;
  /**
   * @minimum 1
   * @maximum 9007199254740991
   */
  sets: number;
  /**
   * @minimum 1
   * @maximum 9007199254740991
   */
  reps: number;
  /**
   * @minimum 1
   * @maximum 9007199254740991
   */
  restTimeInSeconds: number;
};

export type CreateWorkoutPlanBodyWorkoutDaysItem = {
  /** @minLength 1 */
  name: string;
  weekDay: CreateWorkoutPlanBodyWorkoutDaysItemWeekDay;
  isRest?: boolean;
  coverImageUrl?: string;
  /**
   * @minimum 1
   * @maximum 9007199254740991
   */
  estimatedDurationInSeconds: number;
  exercises: CreateWorkoutPlanBodyWorkoutDaysItemExercisesItem[];
};

export type CreateWorkoutPlanBody = {
  /** @minLength 1 */
  name: string;
  workoutDays: CreateWorkoutPlanBodyWorkoutDaysItem[];
};

export type CreateWorkoutPlan201WorkoutDaysItemWeekDay = typeof CreateWorkoutPlan201WorkoutDaysItemWeekDay[keyof typeof CreateWorkoutPlan201WorkoutDaysItemWeekDay];


export const CreateWorkoutPlan201WorkoutDaysItemWeekDay = {
  MONDAY: 'MONDAY',
  TUESDAY: 'TUESDAY',
  WEDNESDAY: 'WEDNESDAY',
  THURSDAY: 'THURSDAY',
  FRIDAY: 'FRIDAY',
  SATURDAY: 'SATURDAY',
  SUNDAY: 'SUNDAY',
} as const;

export type CreateWorkoutPlan201WorkoutDaysItemExercisesItem = {
  /**
   * @minimum 0
   * @maximum 9007199254740991
   */
  order: number;
  /** @minLength 1 */
  name: string;
  /**
   * @minimum 1
   * @maximum 9007199254740991
   */
  sets: number;
  /**
   * @minimum 1
   * @maximum 9007199254740991
   */
  reps: number;
  /**
   * @minimum 1
   * @maximum 9007199254740991
   */
  restTimeInSeconds: number;
};

export type CreateWorkoutPlan201WorkoutDaysItem = {
  /** @minLength 1 */
  name: string;
  weekDay: CreateWorkoutPlan201WorkoutDaysItemWeekDay;
  isRest: boolean;
  coverImageUrl?: string;
  /**
   * @minimum 1
   * @maximum 9007199254740991
   */
  estimatedDurationInSeconds: number;
  exercises: CreateWorkoutPlan201WorkoutDaysItemExercisesItem[];
};

export type CreateWorkoutPlan201 = {
  /** @pattern ^[cC][^\s-]{8,}$ */
  id: string;
  /** @minLength 1 */
  name: string;
  workoutDays: CreateWorkoutPlan201WorkoutDaysItem[];
};

export type CreateWorkoutPlan400 = {
  message: string;
  code: string;
};

export type CreateWorkoutPlan401 = {
  message: string;
  code: string;
};

export type CreateWorkoutPlan404 = {
  message: string;
  code: string;
};

export type CreateWorkoutPlan500 = {
  message: string;
  code: string;
};

export type GetWorkoutPlanById200WorkoutDaysItemWeekDay = typeof GetWorkoutPlanById200WorkoutDaysItemWeekDay[keyof typeof GetWorkoutPlanById200WorkoutDaysItemWeekDay];


export const GetWorkoutPlanById200WorkoutDaysItemWeekDay = {
  MONDAY: 'MONDAY',
  TUESDAY: 'TUESDAY',
  WEDNESDAY: 'WEDNESDAY',
  THURSDAY: 'THURSDAY',
  FRIDAY: 'FRIDAY',
  SATURDAY: 'SATURDAY',
  SUNDAY: 'SUNDAY',
} as const;

export type GetWorkoutPlanById200WorkoutDaysItem = {
  /** @pattern ^[cC][^\s-]{8,}$ */
  id: string;
  weekDay: GetWorkoutPlanById200WorkoutDaysItemWeekDay;
  name: string;
  isRest: boolean;
  coverImageUrl?: string;
  /** @maximum 9007199254740991 */
  estimatedDurationInSeconds: number;
  /**
   * @minimum 0
   * @maximum 9007199254740991
   */
  exercisesCount: number;
};

export type GetWorkoutPlanById200 = {
  /** @pattern ^[cC][^\s-]{8,}$ */
  id: string;
  name: string;
  workoutDays: GetWorkoutPlanById200WorkoutDaysItem[];
};

export type GetWorkoutPlanById401 = {
  message: string;
  code: string;
};

export type GetWorkoutPlanById403 = {
  message: string;
  code: string;
};

export type GetWorkoutPlanById404 = {
  message: string;
  code: string;
};

export type GetWorkoutPlanById500 = {
  message: string;
  code: string;
};

export type GetWorkoutDayById200ExercisesItem = {
  /** @pattern ^[cC][^\s-]{8,}$ */
  id: string;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  order: number;
  name: string;
  /** @maximum 9007199254740991 */
  sets: number;
  /** @maximum 9007199254740991 */
  reps: number;
  /** @maximum 9007199254740991 */
  restTimeInSeconds: number;
  /** @pattern ^[cC][^\s-]{8,}$ */
  workoutDayId: string;
};

export type GetWorkoutDayById200WeekDay = typeof GetWorkoutDayById200WeekDay[keyof typeof GetWorkoutDayById200WeekDay];


export const GetWorkoutDayById200WeekDay = {
  MONDAY: 'MONDAY',
  TUESDAY: 'TUESDAY',
  WEDNESDAY: 'WEDNESDAY',
  THURSDAY: 'THURSDAY',
  FRIDAY: 'FRIDAY',
  SATURDAY: 'SATURDAY',
  SUNDAY: 'SUNDAY',
} as const;

export type GetWorkoutDayById200SessionsItem = {
  /** @pattern ^[cC][^\s-]{8,}$ */
  id: string;
  /** @pattern ^[cC][^\s-]{8,}$ */
  workoutDayId: string;
  startedAt?: string;
  completedAt?: string;
};

export type GetWorkoutDayById200 = {
  /** @pattern ^[cC][^\s-]{8,}$ */
  id: string;
  name: string;
  isRest: boolean;
  coverImageUrl?: string;
  /** @maximum 9007199254740991 */
  estimatedDurationInSeconds: number;
  exercises: GetWorkoutDayById200ExercisesItem[];
  weekDay: GetWorkoutDayById200WeekDay;
  sessions: GetWorkoutDayById200SessionsItem[];
};

export type GetWorkoutDayById401 = {
  message: string;
  code: string;
};

export type GetWorkoutDayById403 = {
  message: string;
  code: string;
};

export type GetWorkoutDayById404 = {
  message: string;
  code: string;
};

export type GetWorkoutDayById500 = {
  message: string;
  code: string;
};

export type StartWorkoutSession201 = {
  /** @pattern ^[cC][^\s-]{8,}$ */
  userWorkoutSessionId: string;
};

export type StartWorkoutSession401 = {
  message: string;
  code: string;
};

export type StartWorkoutSession403 = {
  message: string;
  code: string;
};

export type StartWorkoutSession404 = {
  message: string;
  code: string;
};

export type StartWorkoutSession409 = {
  message: string;
  code: string;
};

export type StartWorkoutSession500 = {
  message: string;
  code: string;
};

export type UpdateWorkoutSessionBody = {
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$ */
  completedAt: string;
};

export type UpdateWorkoutSession200 = {
  /** @pattern ^[cC][^\s-]{8,}$ */
  id: string;
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$ */
  completedAt: string;
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$ */
  startedAt: string;
};

export type UpdateWorkoutSession401 = {
  message: string;
  code: string;
};

export type UpdateWorkoutSession403 = {
  message: string;
  code: string;
};

export type UpdateWorkoutSession404 = {
  message: string;
  code: string;
};

export type UpdateWorkoutSession500 = {
  message: string;
  code: string;
};

export type GetStatsParams = {
/**
 * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))$
 */
from: string;
/**
 * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))$
 */
to: string;
};

export type GetStats200ConsistencyByDay = {[key: string]: {
  workoutDayCompleted: boolean;
  workoutDayStarted: boolean;
}};

export type GetStats200 = {
  /**
   * @minimum 0
   * @maximum 9007199254740991
   */
  workoutStreak: number;
  consistencyByDay: GetStats200ConsistencyByDay;
  /**
   * @minimum 0
   * @maximum 9007199254740991
   */
  completedWorkoutsCount: number;
  /**
   * @minimum 0
   * @maximum 1
   */
  conclusionRate: number;
  /**
   * @minimum 0
   * @maximum 9007199254740991
   */
  totalTimeInSeconds: number;
};

export type GetStats400 = {
  message: string;
  code: string;
};

export type GetStats401 = {
  message: string;
  code: string;
};

export type GetStats500 = {
  message: string;
  code: string;
};

/**
 * @nullable
 */
export type GetUserTrainData200 = {
  userId: string;
  userName: string;
  /**
   * @minimum 0
   * @maximum 9007199254740991
   */
  weightInGrams: number;
  /**
   * @minimum 1
   * @maximum 9007199254740991
   */
  heightInCentimeters: number;
  /**
   * @minimum 1
   * @maximum 9007199254740991
   */
  age: number;
  /**
   * @minimum 0
   * @maximum 100
   */
  bodyFatPercentage: number;
} | null;

export type GetUserTrainData401 = {
  message: string;
  code: string;
};

export type GetUserTrainData500 = {
  message: string;
  code: string;
};

export type ChatWithIABody = {
  messages: unknown[];
};

export type ChatWithIA401 = {
  message: string;
  code: string;
};

export type ChatWithIA500 = {
  message: string;
  code: string;
};

/**
 * Returns the data needed to fill the home page for the authenticated user
 * @summary Get home page data
 */
export type getHomeDataResponse200 = {
  data: GetHomeData200
  status: 200
}

export type getHomeDataResponse400 = {
  data: GetHomeData400
  status: 400
}

export type getHomeDataResponse401 = {
  data: GetHomeData401
  status: 401
}

export type getHomeDataResponse500 = {
  data: GetHomeData500
  status: 500
}
    
export type getHomeDataResponseSuccess = (getHomeDataResponse200) & {
  headers: Headers;
};
export type getHomeDataResponseError = (getHomeDataResponse400 | getHomeDataResponse401 | getHomeDataResponse500) & {
  headers: Headers;
};

export type getHomeDataResponse = (getHomeDataResponseSuccess | getHomeDataResponseError)

export const getGetHomeDataUrl = (date: string,) => {


  

  return `/home/${date}`
}

export const getHomeData = async (date: string, options?: RequestInit): Promise<getHomeDataResponse> => {
  
  return customFetch<getHomeDataResponse>(getGetHomeDataUrl(date),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * Lista os planos de treino do usuário. Filtro active opcional: ?active=true (apenas ativos), ?active=false (apenas inativos). Sem o filtro, retorna todos.
 * @summary List workout plans
 */
export type listWorkoutPlansResponse200 = {
  data: ListWorkoutPlans200
  status: 200
}

export type listWorkoutPlansResponse401 = {
  data: ListWorkoutPlans401
  status: 401
}

export type listWorkoutPlansResponse500 = {
  data: ListWorkoutPlans500
  status: 500
}
    
export type listWorkoutPlansResponseSuccess = (listWorkoutPlansResponse200) & {
  headers: Headers;
};
export type listWorkoutPlansResponseError = (listWorkoutPlansResponse401 | listWorkoutPlansResponse500) & {
  headers: Headers;
};

export type listWorkoutPlansResponse = (listWorkoutPlansResponseSuccess | listWorkoutPlansResponseError)

export const getListWorkoutPlansUrl = (params?: ListWorkoutPlansParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/workout-plans/?${stringifiedParams}` : `/workout-plans/`
}

export const listWorkoutPlans = async (params?: ListWorkoutPlansParams, options?: RequestInit): Promise<listWorkoutPlansResponse> => {
  
  return customFetch<listWorkoutPlansResponse>(getListWorkoutPlansUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * Create a new workout plan
 * @summary Create a new workout plan
 */
export type createWorkoutPlanResponse201 = {
  data: CreateWorkoutPlan201
  status: 201
}

export type createWorkoutPlanResponse400 = {
  data: CreateWorkoutPlan400
  status: 400
}

export type createWorkoutPlanResponse401 = {
  data: CreateWorkoutPlan401
  status: 401
}

export type createWorkoutPlanResponse404 = {
  data: CreateWorkoutPlan404
  status: 404
}

export type createWorkoutPlanResponse500 = {
  data: CreateWorkoutPlan500
  status: 500
}
    
export type createWorkoutPlanResponseSuccess = (createWorkoutPlanResponse201) & {
  headers: Headers;
};
export type createWorkoutPlanResponseError = (createWorkoutPlanResponse400 | createWorkoutPlanResponse401 | createWorkoutPlanResponse404 | createWorkoutPlanResponse500) & {
  headers: Headers;
};

export type createWorkoutPlanResponse = (createWorkoutPlanResponseSuccess | createWorkoutPlanResponseError)

export const getCreateWorkoutPlanUrl = () => {


  

  return `/workout-plans/`
}

export const createWorkoutPlan = async (createWorkoutPlanBody: CreateWorkoutPlanBody, options?: RequestInit): Promise<createWorkoutPlanResponse> => {
  
  return customFetch<createWorkoutPlanResponse>(getCreateWorkoutPlanUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createWorkoutPlanBody,)
  }
);}



/**
 * Retorna o plano de treino com seus dias (exercisesCount)
 * @summary Get workout plan by ID
 */
export type getWorkoutPlanByIdResponse200 = {
  data: GetWorkoutPlanById200
  status: 200
}

export type getWorkoutPlanByIdResponse401 = {
  data: GetWorkoutPlanById401
  status: 401
}

export type getWorkoutPlanByIdResponse403 = {
  data: GetWorkoutPlanById403
  status: 403
}

export type getWorkoutPlanByIdResponse404 = {
  data: GetWorkoutPlanById404
  status: 404
}

export type getWorkoutPlanByIdResponse500 = {
  data: GetWorkoutPlanById500
  status: 500
}
    
export type getWorkoutPlanByIdResponseSuccess = (getWorkoutPlanByIdResponse200) & {
  headers: Headers;
};
export type getWorkoutPlanByIdResponseError = (getWorkoutPlanByIdResponse401 | getWorkoutPlanByIdResponse403 | getWorkoutPlanByIdResponse404 | getWorkoutPlanByIdResponse500) & {
  headers: Headers;
};

export type getWorkoutPlanByIdResponse = (getWorkoutPlanByIdResponseSuccess | getWorkoutPlanByIdResponseError)

export const getGetWorkoutPlanByIdUrl = (id: string,) => {


  

  return `/workout-plans/${id}`
}

export const getWorkoutPlanById = async (id: string, options?: RequestInit): Promise<getWorkoutPlanByIdResponse> => {
  
  return customFetch<getWorkoutPlanByIdResponse>(getGetWorkoutPlanByIdUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * Retorna o dia de treino com seus exercícios e sessões do usuário
 * @summary Get workout day by ID
 */
export type getWorkoutDayByIdResponse200 = {
  data: GetWorkoutDayById200
  status: 200
}

export type getWorkoutDayByIdResponse401 = {
  data: GetWorkoutDayById401
  status: 401
}

export type getWorkoutDayByIdResponse403 = {
  data: GetWorkoutDayById403
  status: 403
}

export type getWorkoutDayByIdResponse404 = {
  data: GetWorkoutDayById404
  status: 404
}

export type getWorkoutDayByIdResponse500 = {
  data: GetWorkoutDayById500
  status: 500
}
    
export type getWorkoutDayByIdResponseSuccess = (getWorkoutDayByIdResponse200) & {
  headers: Headers;
};
export type getWorkoutDayByIdResponseError = (getWorkoutDayByIdResponse401 | getWorkoutDayByIdResponse403 | getWorkoutDayByIdResponse404 | getWorkoutDayByIdResponse500) & {
  headers: Headers;
};

export type getWorkoutDayByIdResponse = (getWorkoutDayByIdResponseSuccess | getWorkoutDayByIdResponseError)

export const getGetWorkoutDayByIdUrl = (workoutPlanId: string,
    workoutDayId: string,) => {


  

  return `/workout-plans/${workoutPlanId}/days/${workoutDayId}`
}

export const getWorkoutDayById = async (workoutPlanId: string,
    workoutDayId: string, options?: RequestInit): Promise<getWorkoutDayByIdResponse> => {
  
  return customFetch<getWorkoutDayByIdResponse>(getGetWorkoutDayByIdUrl(workoutPlanId,workoutDayId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * Start a workout session
 * @summary Start a workout session
 */
export type startWorkoutSessionResponse201 = {
  data: StartWorkoutSession201
  status: 201
}

export type startWorkoutSessionResponse401 = {
  data: StartWorkoutSession401
  status: 401
}

export type startWorkoutSessionResponse403 = {
  data: StartWorkoutSession403
  status: 403
}

export type startWorkoutSessionResponse404 = {
  data: StartWorkoutSession404
  status: 404
}

export type startWorkoutSessionResponse409 = {
  data: StartWorkoutSession409
  status: 409
}

export type startWorkoutSessionResponse500 = {
  data: StartWorkoutSession500
  status: 500
}
    
export type startWorkoutSessionResponseSuccess = (startWorkoutSessionResponse201) & {
  headers: Headers;
};
export type startWorkoutSessionResponseError = (startWorkoutSessionResponse401 | startWorkoutSessionResponse403 | startWorkoutSessionResponse404 | startWorkoutSessionResponse409 | startWorkoutSessionResponse500) & {
  headers: Headers;
};

export type startWorkoutSessionResponse = (startWorkoutSessionResponseSuccess | startWorkoutSessionResponseError)

export const getStartWorkoutSessionUrl = (workoutPlanId: string,
    workoutDayId: string,) => {


  

  return `/workout-plans/${workoutPlanId}/days/${workoutDayId}/sessions`
}

export const startWorkoutSession = async (workoutPlanId: string,
    workoutDayId: string, options?: RequestInit): Promise<startWorkoutSessionResponse> => {
  
  return customFetch<startWorkoutSessionResponse>(getStartWorkoutSessionUrl(workoutPlanId,workoutDayId),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}



/**
 * Atualiza uma sessão de treino específica
 * @summary Update a workout session
 */
export type updateWorkoutSessionResponse200 = {
  data: UpdateWorkoutSession200
  status: 200
}

export type updateWorkoutSessionResponse401 = {
  data: UpdateWorkoutSession401
  status: 401
}

export type updateWorkoutSessionResponse403 = {
  data: UpdateWorkoutSession403
  status: 403
}

export type updateWorkoutSessionResponse404 = {
  data: UpdateWorkoutSession404
  status: 404
}

export type updateWorkoutSessionResponse500 = {
  data: UpdateWorkoutSession500
  status: 500
}
    
export type updateWorkoutSessionResponseSuccess = (updateWorkoutSessionResponse200) & {
  headers: Headers;
};
export type updateWorkoutSessionResponseError = (updateWorkoutSessionResponse401 | updateWorkoutSessionResponse403 | updateWorkoutSessionResponse404 | updateWorkoutSessionResponse500) & {
  headers: Headers;
};

export type updateWorkoutSessionResponse = (updateWorkoutSessionResponseSuccess | updateWorkoutSessionResponseError)

export const getUpdateWorkoutSessionUrl = (workoutPlanId: string,
    workoutDayId: string,
    sessionId: string,) => {


  

  return `/workout-plans/${workoutPlanId}/days/${workoutDayId}/sessions/${sessionId}`
}

export const updateWorkoutSession = async (workoutPlanId: string,
    workoutDayId: string,
    sessionId: string,
    updateWorkoutSessionBody: UpdateWorkoutSessionBody, options?: RequestInit): Promise<updateWorkoutSessionResponse> => {
  
  return customFetch<updateWorkoutSessionResponse>(getUpdateWorkoutSessionUrl(workoutPlanId,workoutDayId,sessionId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateWorkoutSessionBody,)
  }
);}



/**
 * Returns workout statistics for the authenticated user within the specified date range
 * @summary Get user statistics
 */
export type getStatsResponse200 = {
  data: GetStats200
  status: 200
}

export type getStatsResponse400 = {
  data: GetStats400
  status: 400
}

export type getStatsResponse401 = {
  data: GetStats401
  status: 401
}

export type getStatsResponse500 = {
  data: GetStats500
  status: 500
}
    
export type getStatsResponseSuccess = (getStatsResponse200) & {
  headers: Headers;
};
export type getStatsResponseError = (getStatsResponse400 | getStatsResponse401 | getStatsResponse500) & {
  headers: Headers;
};

export type getStatsResponse = (getStatsResponseSuccess | getStatsResponseError)

export const getGetStatsUrl = (params: GetStatsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/stats/?${stringifiedParams}` : `/stats/`
}

export const getStats = async (params: GetStatsParams, options?: RequestInit): Promise<getStatsResponse> => {
  
  return customFetch<getStatsResponse>(getGetStatsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * Retorna os dados de treino do usuário autenticado. Retorna null (200) se os dados ainda não existirem.
 * @summary Get current user train data
 */
export type getUserTrainDataResponse200 = {
  data: GetUserTrainData200
  status: 200
}

export type getUserTrainDataResponse401 = {
  data: GetUserTrainData401
  status: 401
}

export type getUserTrainDataResponse500 = {
  data: GetUserTrainData500
  status: 500
}
    
export type getUserTrainDataResponseSuccess = (getUserTrainDataResponse200) & {
  headers: Headers;
};
export type getUserTrainDataResponseError = (getUserTrainDataResponse401 | getUserTrainDataResponse500) & {
  headers: Headers;
};

export type getUserTrainDataResponse = (getUserTrainDataResponseSuccess | getUserTrainDataResponseError)

export const getGetUserTrainDataUrl = () => {


  

  return `/me`
}

export const getUserTrainData = async ( options?: RequestInit): Promise<getUserTrainDataResponse> => {
  
  return customFetch<getUserTrainDataResponse>(getGetUserTrainDataUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Chat com personal trainer virtual
 */
export type chatWithIAResponse200 = {
  data: unknown
  status: 200
}

export type chatWithIAResponse401 = {
  data: ChatWithIA401
  status: 401
}

export type chatWithIAResponse500 = {
  data: ChatWithIA500
  status: 500
}
    
export type chatWithIAResponseSuccess = (chatWithIAResponse200) & {
  headers: Headers;
};
export type chatWithIAResponseError = (chatWithIAResponse401 | chatWithIAResponse500) & {
  headers: Headers;
};

export type chatWithIAResponse = (chatWithIAResponseSuccess | chatWithIAResponseError)

export const getChatWithIAUrl = () => {


  

  return `/ia/`
}

export const chatWithIA = async (chatWithIABody: ChatWithIABody, options?: RequestInit): Promise<chatWithIAResponse> => {
  
  return customFetch<chatWithIAResponse>(getChatWithIAUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      chatWithIABody,)
  }
);}



export type getApiAuthResponse200 = {
  data: void
  status: 200
}
    
export type getApiAuthResponseSuccess = (getApiAuthResponse200) & {
  headers: Headers;
};
;

export type getApiAuthResponse = (getApiAuthResponseSuccess)

export const getGetApiAuthUrl = (: string,) => {


  

  return `/api/auth/${}`
}

export const getApiAuth = async (: string, options?: RequestInit): Promise<getApiAuthResponse> => {
  
  return customFetch<getApiAuthResponse>(getGetApiAuthUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



export type postApiAuthResponse200 = {
  data: void
  status: 200
}
    
export type postApiAuthResponseSuccess = (postApiAuthResponse200) & {
  headers: Headers;
};
;

export type postApiAuthResponse = (postApiAuthResponseSuccess)

export const getPostApiAuthUrl = (: string,) => {


  

  return `/api/auth/${}`
}

export const postApiAuth = async (: string, options?: RequestInit): Promise<postApiAuthResponse> => {
  
  return customFetch<postApiAuthResponse>(getPostApiAuthUrl(),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}
