import type { Metadata } from "next";
import { Geist, Geist_Mono, JetBrains_Mono } from "next/font/google";
import { Suspense } from "react";
import { NuqsAdapter } from "nuqs/adapters/next";
import "./globals.css";
import { cn } from "@/app/_lib/utils";
import { FitAiChatRoot } from "@/app/_components/chat/fit-ai-chat-root";
import { Toaster } from "@/app/_components/ui/sonner";

const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        geistSans.variable,
        geistMono.variable,
        "font-mono",
        jetbrainsMono.variable,
      )}
    >
      <body className="min-h-dvh flex flex-col bg-background">
        <NuqsAdapter>
          <div className="flex min-h-dvh w-full flex-1 flex-col">
            {children}
            <Suspense fallback={null}>
              <FitAiChatRoot />
            </Suspense>
          </div>
        </NuqsAdapter>
        <Toaster />
      </body>
    </html>
  );
}
